version: "3.8"

services:
  server:
    build: .
    restart: always
    ports:
      - "3001"
    container_name: nestjs-server

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx-nestjs-server
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "81:81"
    depends_on:
      - server

