POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE4LCJlbWFpbCI6Im1hcmtAZG9lLmNvbSIsImlhdCI6MTc3MzkwNTg4MSwiZXhwIjoxNzczOTA5NDgxLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.FJIXV1IYs8ImBCdyqYpTvvfnF2s2wAeL2U4tFuCcV8U

{
  "title": "Hi, nameasdf",
  "postType": "post",
  "slug": "new-with-nestjs-with-author-12",
  "status": "draft",
  "content": "test content",
  "schema": "{\"key\": \"passport\", \"value\": \"ty45343339\"}",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "metaOptions": {
    "metaValue": "{\"key\": \"passport\", \"value\": \"ty45343339\"}"
  },
  "tags": []
}