POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE4LCJlbWFpbCI6Im1hcmtAZG9lLmNvbSIsImlhdCI6MTc3MjM3NTM3MiwiZXhwIjoxNzcyMzc4OTcyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.I9jNjBH3fbIhsFFZdEXK5UpvuRvq_Th5HaHczxt8k1c

{
  "title": "Hi, nameasdf",
  "postType": "post",
  "slug": "new-with-nestjs-with-author-12",
  "status": "draft",
  "content": "test content",
  "schema": "{\"key\": \"passport\", \"value\": \"ty45343339\"}",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2026-03-26",
  "metaOptions": {
    "metaValue": "{\"key\": \"passport\", \"value\": \"ty45343339\"}"
  },
  "tags": [4]
}