PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id": 31,
  "title": "What's a new with NestJS with Typescript",
  "postType": "post",
  "slug": "new-with-nestjs",
  "status": "draft",
  "content": "test content",
  "schema": "{\r\n \"@context\": \"https\/\/schema.org\" \r\n}",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2026-01-26",
  "tags": [3,4,5],
  "metaOptions": {
    "metaValue": "{\"sidebarEnabled\": true}"
  }
}