POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Hi, name",
  "postType": "post",
  "slug": "new-with-nestjs-with-author-12",
  "status": "draft",
  "content": "test content",
  "schema": "{\"key\": \"passport\", \"value\": \"ty45343339\"}",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2026-01-26",
  //"tags": ["dev", "nestjs", "typescript"],
  "metaOptions": {
    "metaValue": "{\"key\": \"passport\", \"value\": \"ty45343339\"}"
  },
  "authorId": 2,
  "tags": [4]
}