GET http://localhost:3000/users HTTP/1.1


###
GET http://localhost:3000/users/123
?limit=12
&age=1

###
GET http://localhost:3000/users/hello/123
?limit=10
&offset=20 HTTP/1.1


###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "firstName": "Mark",
  "lastName": "Kambayashi",
  "email": "mark@doe.com",
  "password": "Password123!"
}


###
POST http://localhost:3000/users/create-many HTTP/1.1
Content-Type: application/json

{
  "users": [
    {
      "firstName": "Kiyo",
      "lastName": "Kambayashi",
      "email": "johnfew@doe.com",
      "password": "Password123!"
    },
    {
      "firstName": "Nana",
      "lastName": "Kambayashi",
      "email": "johnasdf@doe.com",
      "password": "Password123!"
    },
    {
      "firstName": "KiyNana",
      "lastName": "Kambayashi",
      "email": "johnasdewaff@doe.com",
      "password": "Password123!"
    }
  ]
}