GET http://localhost:3000/users HTTP/1.1


###
GET http://localhost:3000/users/123
?limit=12
&age=1

###
GET http://localhost:3000/users/hello/123
?limit=10
&offset=20 HTTP/1.1


###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE4LCJlbWFpbCI6Im1hcmtAZG9lLmNvbSIsImlhdCI6MTc3MjI4NzU3MCwiZXhwIjoxNzcyMjkxMTcwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.Voyis5w75W_NcipaOZ4c12_g9X8CF1mhEHm1jDzz05s

{
  "firstName": "Mark",
  "lastName": "Kambayashi",
  "email": "mark@doe.com",
  "password": "Password123!"
}


###
POST http://localhost:3000/users/create-many HTTP/1.1
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE4LCJlbWFpbCI6Im1hcmtAZG9lLmNvbSIsImlhdCI6MTc3MjE2MzM0NywiZXhwIjoxNzcyMTY2OTQ3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.xAxle-UpvMjUPU78SzC-6tDsFvfD8K8Zfx30ufOV3mk

{
  "users": [
    {
      "firstName": "Kiyo",
      "lastName": "Kambayashi",
      "email": "johnfew@doe.com",
      "password": "Password123!"
    },
    {
      "firstName": "Nana",
      "lastName": "Kambayashi",
      "email": "johnasdf@doe.com",
      "password": "Password123!"
    },
    {
      "firstName": "KiyNana",
      "lastName": "Kambayashi",
      "email": "johnasdewaff@doe.com",
      "password": "Password123!"
    }
  ]
}