
###
POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE4LCJpYXQiOjE3NzIzODA1MDMsImV4cCI6MTc3MjQ2NjkwMywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.fNqxo_rcP8jnErpi0AL3kvIWGxyOZqaAgetYsAUIGO8"
}